CREATE TABLE  (
   int(11) NOT NULL AUTO_INCREMENT,
   int(11) NOT NULL,
   datetime NOT NULL DEFAULT current_timestamp(),
   date NOT NULL,
   time NOT NULL,
  PRIMARY KEY (),
  KEY  (),
  CONSTRAINT  FOREIGN KEY () REFERENCES  () ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
