CREATE TABLE  (
   int(11) NOT NULL AUTO_INCREMENT,
   int(11) NOT NULL,
   int(11) NOT NULL,
   date NOT NULL,
   date NOT NULL,
   date DEFAULT NULL,
  PRIMARY KEY (),
  KEY  (),
  KEY  (),
  CONSTRAINT  FOREIGN KEY () REFERENCES  (),
  CONSTRAINT  FOREIGN KEY () REFERENCES  ()
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
