CREATE TABLE  (
   int(11) NOT NULL AUTO_INCREMENT,
   varchar(50) NOT NULL UNIQUE,
   varchar(50) NOT NULL UNIQUE,
  PRIMARY KEY ()
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
